import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { sendEmail } from "@/lib/mailer";

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { personal, data, pdfBase64 } = body;

        // 1. Save to Resume dataset
        const resume = await prisma.resume.create({
            data: {
                name: personal?.fullName || "Unknown",
                email: personal?.email || "Unknown",
                phone: personal?.phone,
                details: JSON.stringify(data),
                // if we had a cloud storage we'd upload pdfBase64 and store URL
            }
        });

        // 2. Email Super User
        // Find super users
        const superUsers = await prisma.user.findMany({
            where: { role: 'SUPERUSER' }
        });

        let attachments: any[] = [];
        if (pdfBase64) {
             const base64Data = pdfBase64.replace(/^data:application\/pdf;base64,/, "");
             attachments.push({
                 filename: `${personal?.fullName || 'Resume'}.pdf`,
                 content: base64Data,
                 encoding: 'base64'
             });
        }

        for (const su of superUsers) {
            if (su.email) {
                await sendEmail(
                    su.email,
                    `New Resume Generated: ${personal?.fullName}`,
                    `A new resume was generated by ${personal?.fullName}. Find it attached.`,
                    `<p>A new resume was generated by <strong>${personal?.fullName}</strong>.</p>`,
                    attachments
                );
            }
        }

        return NextResponse.json({ success: true, resumeId: resume.id });
    } catch (error) {
        console.error("Resume generation error:", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}
